"""Public interface for Elysia's chat domain model."""

from .domain import (
    CHAT_SESSION_SCHEMA_VERSION,
    AttachmentId,
    AttachmentMetadata,
    ChatId,
    ChatMessage,
    ChatMessageId,
    ChatMessageRole,
    ChatModelSettings,
    ChatSession,
    ChatSessionMeta,
    ChatSummary,
    ConversationMode,
    ProjectId,
    create_attachment_metadata,
    create_chat_message,
    create_chat_session,
    generate_attachment_id,
    generate_chat_id,
    generate_chat_message_id,
)

__all__ = [
    "CHAT_SESSION_SCHEMA_VERSION",
    "AttachmentId",
    "AttachmentMetadata",
    "ChatId",
    "ChatMessage",
    "ChatMessageId",
    "ChatMessageRole",
    "ChatModelSettings",
    "ChatSession",
    "ChatSessionMeta",
    "ChatSummary",
    "ConversationMode",
    "ProjectId",
    "create_attachment_metadata",
    "create_chat_message",
    "create_chat_session",
    "generate_attachment_id",
    "generate_chat_id",
    "generate_chat_message_id",
]