"""Trusted, bounded document loading over path-private stored files."""

from .domain import (
    DOCUMENT_SCHEMA_VERSION,
    DocumentBlock,
    DocumentBlockKind,
    DocumentFormat,
    DocumentLoadLimits,
    DocumentSource,
    DocumentTable,
    DocumentTitle,
    DocumentTitleSource,
    LoadedDocument,
)
from .exceptions import (
    DocumentContentLimitError,
    DocumentCorruptError,
    DocumentEmptyError,
    DocumentEncryptedError,
    DocumentError,
    DocumentLimitError,
    DocumentLoadFailedError,
    DocumentNotFoundError,
    DocumentReadError,
    DocumentTooLargeError,
    DocumentUnsupportedFeatureError,
    DocumentUnsupportedFormatError,
    DocumentValidationError,
)
from .protocol import DocumentLoader, DocumentRoute
from .service import DocumentFileRepository, DocumentLoaderService

__all__ = [
    "DOCUMENT_SCHEMA_VERSION",
    "DocumentBlock",
    "DocumentBlockKind",
    "DocumentContentLimitError",
    "DocumentCorruptError",
    "DocumentEmptyError",
    "DocumentEncryptedError",
    "DocumentError",
    "DocumentFormat",
    "DocumentFileRepository",
    "DocumentLimitError",
    "DocumentLoadFailedError",
    "DocumentLoadLimits",
    "DocumentLoader",
    "DocumentLoaderService",
    "DocumentNotFoundError",
    "DocumentReadError",
    "DocumentRoute",
    "DocumentSource",
    "DocumentTable",
    "DocumentTitle",
    "DocumentTitleSource",
    "DocumentTooLargeError",
    "DocumentUnsupportedFeatureError",
    "DocumentUnsupportedFormatError",
    "DocumentValidationError",
    "LoadedDocument",
]
