"""Expose the versioned Electron-to-Python desktop protocol."""

from .contracts import (
    MAX_MESSAGE_LENGTH,
    MAX_PROTOCOL_FRAME_BYTES,
    PROTOCOL_NAME,
    PROTOCOL_VERSION,
    SUPPORTED_METHODS,
    ClientRequest,
    ErrorResponse,
    EventMessage,
    PermissionMessage,
    ProgressMessage,
    ProtocolMethod,
    ProtocolValidationError,
    ServerMessage,
    StreamChunkMessage,
    SuccessResponse,
    build_error_response,
    build_event,
    build_permission,
    build_progress,
    build_request,
    build_stream_chunk,
    build_success_response,
    parse_client_request,
    parse_server_message,
)

__all__ = [
    "MAX_MESSAGE_LENGTH",
    "MAX_PROTOCOL_FRAME_BYTES",
    "PROTOCOL_NAME",
    "PROTOCOL_VERSION",
    "SUPPORTED_METHODS",
    "ClientRequest",
    "ErrorResponse",
    "EventMessage",
    "PermissionMessage",
    "ProgressMessage",
    "ProtocolMethod",
    "ProtocolValidationError",
    "ServerMessage",
    "StreamChunkMessage",
    "SuccessResponse",
    "build_error_response",
    "build_event",
    "build_permission",
    "build_progress",
    "build_request",
    "build_stream_chunk",
    "build_success_response",
    "parse_client_request",
    "parse_server_message",
]
